### ISSUE TITLE
currently `./test` script is broken

### ISSUE THREAD

**Issue by edewit** [OASIS-learn-study/minecraft-storeys-maker#349]
Can't run the `./test` script on "develop" branch I get the following error:

```
[17:01:05 ERROR] [LaunchWrapper]: Unable to launch
java.lang.IllegalArgumentException: null
	at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[spongevanilla-1.12.2-7.3.1-RC391.jar:1.12.2-7.3.1-RC391]
	at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[spongevanilla-1.12.2-7.3.1-RC391.jar:1.12.2-7.3.1-RC391]
	at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[spongevanilla-1.12.2-7.3.1-RC391.jar:1.12.2-7.3.1-RC391]
	at org.spongepowered.server.launch.plugin.PluginScanner.scanClassFile(PluginScanner.java:341) ~[spongevanilla-1.12.2-7.3.1-RC391.jar:1.12.2-7.3.1-RC391]
	at org.spongepowered.server.launch.plugin.PluginScanner.scanJar(PluginScanner.java:245) ~[spongevanilla-1.12.2-7.3.1-RC391.jar:1.12.2-7.3.1-RC391]
	at org.spongepowered.server.launch.plugin.PluginScanner.scanDirectory(PluginScanner.java:173) ~[spongevanilla-1.12.2-7.3.1-RC391.jar:1.12.2-7.3.1-RC391]
	at org.spongepowered.server.launch.plugin.VanillaLaunchPluginManager.findPlugins(VanillaLaunchPluginManager.java:66) ~[spongevanilla-1.12.2-7.3.1-RC391.jar:1.12.2-7.3.1-RC391]
	at org.spongepowered.server.launch.VanillaServerTweaker.searchPlugins(VanillaServerTweaker.java:171) ~[spongevanilla-1.12.2-7.3.1-RC391.jar:1.12.2-7.3.1-RC391]
	at org.spongepowered.server.launch.VanillaServerTweaker.injectIntoClassLoader(VanillaServerTweaker.java:94) ~[spongevanilla-1.12.2-7.3.1-RC391.jar:1.12.2-7.3.1-RC391]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) ~[launchwrapper-1.12.jar:?]
	at org.spongepowered.server.launch.VanillaServerMain.main(VanillaServerMain.java:126) ~[spongevanilla-1.12.2-7.3.1-RC391.jar:1.12.2-7.3.1-RC391]
	at org.spongepowered.server.launch.VersionCheckingMain.main(VersionCheckingMain.java:38) ~[spongevanilla-1.12.2-7.3.1-RC391.jar:1.12.2-7.3.1-RC391]
2022-04-09T17:01:05.378Z	WARN	mc-server-runner	sub-process failed	{"exitCode": 1}
2022-04-09T17:01:05.388Z	INFO	mc-server-runner	Done
```

**Comment by edewit** [comment]
did some investigation and I think this commit 78735d201c94cf460fa4bc556e50d3ec64ab1951 introduced it

**Comment by vorburger** [comment]
Duh! See #345... this "just" means there's Java >8 byte code somewhere. 

FYI I had to switch the 1st stage of the multi stage Dockerfile to Java 11 for Checkstyle which doesn't run on Java 8 anymore. But the ./test script uses the Dockerfile-local, so that change has nothing to do with this problem.

The Gradle build has:

    sourceCompatibility = 1.8
    targetCompatibility = 1.8

In one of yesterday's CLs I've moved that and more from allprojects to subprojects. Did that break it?

Or did you do anything like change the primary alternate JDK on your PATH from Java 11 to Java 17 or something like that?

I can further investigate this, probably... Monday or Tuesday night.

**Comment by edewit** [comment]
found out what the problem is if I revert this: https://github.com/OASIS-learn-study/minecraft-storeys-maker/commit/78735d201c94cf460fa4bc556e50d3ec64ab1951#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R24-L38 then it works again

**Comment by edewit** [comment]
The question is why did you move it and what subprojects are effected by this change

**Comment by vorburger** [comment]
> The question is why did you move it 

because to me it seemed _"more logical"_ - but I clearly don't know what I'm doing... 😿 

> and what subprojects are effected by this change

The wrong ones? LOL. -- Given that my plans for this lifetime do not include a Ph.D. in Gradleology anymore, let's just #352 and call this a day.
