### ISSUE TITLE
scratch3/ build not working in local S2I due to Error: Cannot find module './index.js'

### ISSUE THREAD

**Issue by vorburger** [OASIS-learn-study/minecraft-storeys-maker#72]
@edewit while trying to reproduce #70 with a local s2i ([just documented how-to](https://github.com/vorburger/minecraft-storeys-maker/commit/1366e551a2902b554bbdf52ca1b13f5641a40aa1)), after getting past #71, I've hit this problem, which curiously does not appear during the S2I build on OpenShift Online, just local, can't quite explain why:

```
git reset --hard; git clean -d -f -x
s2i build --copy . s2i-minecraft-server minecraft-storeys-maker
...

> Task :scratch:install
> Task :scratch:compileJava NO-SOURCE
> Task :scratch:processResources NO-SOURCE
> Task :scratch:classes UP-TO-DATE
> Task :scratch:jar
> Task :scratch:assemble
> Task :scratch:licenseMain NO-SOURCE
> Task :scratch:licenseTest NO-SOURCE
> Task :scratch:license UP-TO-DATE
> Task :scratch:check
> Task :scratch:build
> Task :scratch3:compileJava NO-SOURCE
> Task :scratch3:processResources NO-SOURCE
> Task :scratch3:classes UP-TO-DATE
> Task :scratch3:jar
> Task :scratch3:nodeSetup

> Task :scratch3:npmSetup
/tmp/src/scratch3/.gradle/npm/npm-v6.0.1/bin/npx -> /tmp/src/scratch3/.gradle/npm/npm-v6.0.1/lib/node_modules/npm/bin/npx-cli.js
/tmp/src/scratch3/.gradle/npm/npm-v6.0.1/bin/npm -> /tmp/src/scratch3/.gradle/npm/npm-v6.0.1/lib/node_modules/npm/bin/npm-cli.js
+ npm@6.0.1
added 682 packages in 7.795s

> Task :scratch3:npmDoInstall0
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> scratch-vm@0.1.0 prepublish /tmp/src/scratch3/build/scratch-vm
> in-publish && npm run build || not-in-publish

module.js:549
throw err;
^

Error: Cannot find module './index.js'
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/tmp/src/scratch3/build/scratch-vm/node_modules/.bin/in-publish:3:17)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
module.js:549
throw err;
^

Error: Cannot find module './index.js'
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/tmp/src/scratch3/build/scratch-vm/node_modules/.bin/not-in-publish:3:17)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scratch-vm@0.1.0 prepublish: `in-publish && npm run build || not-in-publish`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scratch-vm@0.1.0 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /opt/jboss/.npm/_logs/2018-05-27T13_51_57_284Z-debug.log

> Task :scratch3:npmDoInstall0 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':scratch3:npmDoInstall0'.
> Process 'command '/tmp/src/scratch3/.gradle/npm/npm-v6.0.1/bin/npm'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2m 16s
14 actionable tasks: 13 executed, 1 up-to-date
Aborting due to error code 1 for Gradle build
Build failed
ERROR: An error occurred: non-zero (13) exit code from s2i-minecraft-server

```

**Comment by vorburger** [comment]
S2I builds are no longer a priority for this project, ergo closing this old issue.
